image: Visual Studio 2017

before_build:
- cmd: |
    git submodule update --init --recursive

    md build32 & cd build32
    cmake -Wno-error=dev -G "Visual Studio 15 2017" ..
    cd ..

    md build64 & cd build64
    cmake -Wno-error=dev -G "Visual Studio 15 2017 Win64" ..
    cd ..

build_script:
  - cmd: cmake --build build32 --config Release --target zcatch_srv
  - cmd: cmake --build build64 --config Release --target zcatch_srv

test_script:
  - cmd: cmake --build build32 --config Debug --target run_tests
  - cmd: cmake --build build64 --config Debug --target run_tests
  - cmd: cmake --build build32 --config Release --target run_tests
  - cmd: cmake --build build64 --config Release --target run_tests
  - cmd: |
      cd build32
      Release\zcatch_srv shutdown
      cd ..
  - cmd: |
      cd build64
      Release\zcatch_srv shutdown
      cd ..

after_build:
  - cmd: cmake --build build32 --config Release --target package
  - cmd: cmake --build build64 --config Release --target package

environment:
  CFLAGS: /WX
  CXXFLAGS: /WX
  LDFLAGS: /WX
