name: All OS
on:
  push:
    branches: 
      - zCatch-0.7.x
jobs:
  build_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: zCatch-0.7.x
      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install cmake libfreetype6-dev libsdl2-dev -y
          git submodule update --init --recursive

      - name: Create Debug Build Files with CMake
        run: |
          mkdir debug
          cd debug
          cmake -Wno-error=dev -DDOWNLOAD_GTEST=ON -DCLIENT=OFF -DDEV=ON ..
          cd ..

      - name: Create Release Build Files with CMake
        run: |
          mkdir release
          cd release
          cmake -Wno-error=dev -DDOWNLOAD_GTEST=ON -DCLIENT=OFF ..
          cd ..

      - name: Build zCatch Debug
        run: |
          cd debug
          make -j4 zcatch_srv
          ./zcatch_srv shutdown
          cd ..

      - name: Build zCatch Release
        run: |
          cd release
          make -j4 zcatch_srv
          ./zcatch_srv shutdown
          cd ..
      
      - name: Test zCatch Debug
        run: |
          cd debug
          ./zcatch_srv shutdown
          cd ..
        
      - name: Test zCatch Rellease
        run: |
          cd release
          ./zcatch_srv shutdown
          cd .. 
 
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: zCatch-0.7.x

      - name: Prepare
        run: |
          git submodule update --init --recursive

      - name: Create Debug Build Files with CMake x86
        run: |
          md build32_debug
          cd build32_debug
          cmake -Wno-error=dev -DCLIENT=OFF -DDEV=ON -G "Visual Studio 16 2019" ..
          cd ..

      - name: Create Debug Build Files with CMake x64
        run: |
          md build64_debug
          cd build64_debug
          cmake -Wno-error=dev -DCLIENT=OFF -DDEV=ON -G "Visual Studio 16 2019" -A x64 ..
          cd ..

      - name: Create Release Build Files with CMake x86
        run: |
          md build32
          cd build32
          cmake -Wno-error=dev -DCLIENT=OFF -G "Visual Studio 16 2019" ..
          cd ..     
    
      - name: Create Release Build Files with CMake x64
        run: |
          md build64
          cd build64
          cmake -Wno-error=dev -DCLIENT=OFF -G "Visual Studio 16 2019" -A x64 ..
          cd ..

      - name: Build Debug x86
        run: |
          cmake --build build32_debug --config Release --target zcatch_srv

      - name: Build Debug x64
        run: |
          cmake --build build64_debug --config Release --target zcatch_srv

      - name: Build Release x86
        run: |
          cmake --build build32 --config Release --target zcatch_srv

      - name: Build Release x64
        run: |
          cmake --build build64 --config Release --target zcatch_srv
        
      - name: Test
        run: |
          cd build32
          Release\zcatch_srv shutdown
          cd ..
          cd build64
          Release\zcatch_srv shutdown
          cd ..

  build_mac:
    name: Build MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: zCatch-0.7.x
      - name: Prepare
        run: |
          brew install cmake freetype sdl2
          git submodule update --init --recursive

      - name: Create Debug Build Files with CMake
        run: |
          mkdir debug
          cd debug
          cmake -Wno-error=dev -DDOWNLOAD_GTEST=ON -DCFLAGS="-Wdeclaration-after-statement -Werror" -DCXXFLAGS="-Werror" -DCLIENT=OFF -DDEV=ON ..
          cd ..

      - name: Create Release Build Files with CMake
        run: |
          mkdir release
          cd release
          cmake -Wno-error=dev -DDOWNLOAD_GTEST=ON -DCLIENT=OFF ..
          cd ..

      - name: Build Debug
        run: |
          cd debug
          make -j4 zcatch_srv
          cd ..

      - name: Build Release
        run: |
          cd release
          make -j4 zcatch_srv
          cd ..

      - name: Test Debug
        run: |
          cd debug
          make run_tests
          ./zcatch_srv shutdown
          cd ..

      - name: Test Release
        run: |
          cd release
          make run_tests
          ./zcatch_srv shutdown
          cd ..

          